POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "app_id": "1542367205"
}



HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 47
etag: W/"2f-17/M9Ubga5p92H73ogo6o0xE+R0"
date: Mon, 29 Jan 2024 14:12:42 GMT
connection: close
###
POST http://localhost:3000/api/runs HTTP/1.1


HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 544
etag: W/"220-4HlyYD2EIP0yCVM/y81yLtsMVNM"
date: Mon, 29 Jan 2024 09:57:26 GMT
connection: close