POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "app_id": "1529135893"
}
###
POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "from": "21",
    "size": 20,
    "app_id": "1529135893"
}
###
POST http://localhost:3000/api/runs 

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 817
etag: W/"331-w6I6y0cnAyhWBabTddim/zX6bPs"
date: Tue, 30 Jan 2024 19:54:51 GMT
connection: close
###
POST http://localhost:3000/api/get/
Content-Type: application/json
{
    "app_id": "1529135893",
    "run_id": "run_00069"

}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 929
etag: W/"3a1-QQ6BBhpIgOJRs2PVRvdbegSlgVQ"
date: Tue, 30 Jan 2024 20:05:43 GMT
connection: close